- name: "Download Java 8"
  get_url:
    url: https://javadl.oracle.com/webapps/download/AutoDL?BundleId=236877_42970487e3af4f5aa5bca3f542482c60
    dest: /tmp
    headers: {"Cookie": "gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie"}
    validate_certs: no
    mode: 0644
  tags:
    - install_gateway

- name: "Install Java 8"
  yum:
    name: /tmp/jre-8u201-linux-x64.rpm
    state: present
  tags:
    - install_gateway

- name: "Copy RHEL 7 SIO Files"
  copy:
    src: ./files/EMC-ScaleIO-gateway-{{ vxflex_version }}.x86_64.rpm
    dest: /tmp/
    owner: root
    group: root
    mode: 0644
  tags:
    - install_gateway

- name: "Install SIO Gateway"
  yum:
    name: '/tmp/EMC-ScaleIO-gateway-{{ vxflex_version }}.x86_64.rpm'
    state: present
  environment:
    GATEWAY_ADMIN_PASSWORD: "{{ vxflex_gateway_pw }}"
  tags:
    - install_gateway


- name: "Add IP address in the gatewayUser.properties file"
  lineinfile:
    path: /opt/emc/scaleio/gateway/webapps/ROOT/WEB-INF/classes/gatewayUser.properties
    regexp: '^mdm.ip.addresses'
    insertafter: '= '
    line: 'mdm.ip.addresses={{ vxflex_vip_ip }},{{ vxflex_master_mdm_mgmt_ip | join(",") }},{{ vxflex_standby_mdm_mgmt_ip | join(",") }}'
  tags:
    - install_gateway

- name: "Gateway will trust the MDM certificate automatically"
  lineinfile:
    path: /opt/emc/scaleio/gateway/webapps/ROOT/WEB-INF/classes/gatewayUser.properties
    regexp: '^gateway-security.allow_non_secure_communication'
    insertafter: '= '
    line: 'gateway-security.allow_non_secure_communication=true'
  tags:
    - install_gateway

- name: "Gateway will trust the MDM certificate automatically"
  lineinfile:
    path: /opt/emc/scaleio/gateway/webapps/ROOT/WEB-INF/classes/gatewayUser.properties
    regexp: '^security.bypass_certificate_check'
    insertafter: '= '
    line: 'security.bypass_certificate_check=true'
  tags:
    - install_gateway

- name: "Change gateway http port to 8080"
  lineinfile:
    path: /opt/emc/scaleio/gateway/conf/catalina.properties
    regexp: '^http.port'
    insertafter: '= '
    line: "http.port={{ vxflex_gateway_http_port }}"
  tags:
    - install_gateway

- name: "Change gateway https port to 8443"
  lineinfile:
    path: /opt/emc/scaleio/gateway/conf/catalina.properties
    regexp: '^ssl.port'
    insertafter: '= '
    line: "ssl.port={{ vxflex_gateway_https_port }}"
  tags:
    - install_gateway

- name: "Restart Gateway Service"
  systemd:
    name: scaleio-gateway
    enabled: yes
    state: restarted
  tags:
    - install_gateway

- name: "Get ScaleIO token for Auth"
  uri:
    url: "https://{{ vxflex_gateway_ip }}:{{ vxflex_gateway_https_port }}\
    /api/login"
    return_content: yes
    user: "{{ vxflex_gateway_username }}"
    password: "admin"
    force_basic_auth: yes
    validate_certs: False
    status_code:
      - 200
      - 201
      - 202
  register: basic_auth
  ignore_errors: yes
  failed_when: not (basic_auth.status == 200 or basic_auth.status == 401)
  tags:
    - install_gateway

- name: "Change Admin Password"
  uri:
    url: "https://{{ vxflex_gateway_ip }}:{{ vxflex_gateway_https_port }}\
    /api/instances/User/action/setPassword"
    method: POST
    user: "{{ vxflex_gateway_username }}"
    password: "{{ basic_auth.json }}"
    body: {"oldPassword":"{{ vxflex_gateway_username }}",
    "newPassword":"{{ vxflex_gateway_pw }}"}
    force_basic_auth: yes
    body_format: json
    validate_certs: False
    status_code:
      - 200
      - 201
      - 202
  when: basic_auth.status == 200
  changed_when: basic_auth.status == 200
  tags:
    - install_gateway

